CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "levels_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "teacher" int NOT NULL,
  "levels_courses_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(250) NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "student_courses" (
  "student_id" int NOT NULL,
  "courses_id" int NOT NULL
);

ALTER TABLE "student_courses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("levels_courses_id") REFERENCES "levels_courses" ("id");

ALTER TABLE "student_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

-- datos de la tabla categories 

INSERT INTO categories (name) VALUES ('backend');

INSERT INTO categories (name) VALUES ('frontend');

-- datos de la tabla levels_courses

INSERT INTO levels_courses (title) VALUES ('beginner');

INSERT INTO levels_courses (title) VALUES ('intemediate');

INSERT INTO levels_courses (title) VALUES ('advanced');

-- datos de la tabla roles

INSERT INTO roles (name) VALUES('teacher');

INSERT INTO roles (name) VALUES('student');

INSERT INTO roles (name) VALUES('admin');

-- datos de la tabla users 

INSERT INTO users (name, email, password, age, rol_id) VALUES ('jesus', 'nanoperezsanchez@gmail.com', '1234', 31, 2);

INSERT INTO users (name, email, password, age, rol_id) VALUES ('alejandra', 'alejandra0102@gmail.com', '0102', 42, 1);

-- datos de la tabla de courses

INSERT INTO courses (title, description, teacher, levels_courses_id, category_id) VALUES ('react', 'curso introductorio', 1 , 1, 2);

INSERT INTO courses (title, description, teacher, levels_courses_id, category_id) VALUES ('fundamentos', 'curso de fundamento1',1 , 2 , 2);

-- datos de la tabla courses_videos

 INSERT INTO courses_videos (title, url, courses_id) VALUES ('fundamentos_01', 'academlo.com/fundamento/video01', 2);

 INSERT INTO courses_videos (title, url, courses_id) VALUES ('introduccion_react', 'academlo.com/react/video05', 1);

--  datos de la tabla student_courses

INSERT INTO student_courses (student_id, courses_id) VALUES (2, 1);

INSERT INTO student_courses (student_id, courses_id) VALUES (2, 2);
